
// searchListings select data (in hero)
export const selectItemList = {
    property: [
        { value: "Houses", quantity: 24 },
        { value: "Appartments", quantity: 24 },
        { value: "Lands", quantity: 24 },
        { value: "Offices", quantity: 24 },
    ],
    region: [
        { value: "Bronx", quantity: 24 },
        { value: "Brooklyn", quantity: 24 },
        { value: "Long Island", quantity: 24 },
        { value: "Manhattan", quantity: 24 },
        { value: "Queens", quantity: 24 },
        { value: "Staten Island", quantity: 24 },
    ],
    price: [
        { value: 24000},
        { value: 33000},
        { value: 12000},
        { value: 32000},
        { value: 2000},
        { value: 278000},
        { value: 824000},
    ],
}

// sample data for listings
export const listings1 = [
    {
        id: "1",
        title: "Modern Family House",
        address: "New York, NY, USA",
        datePosted: "7 months",
        price: 35000000,
        bed: 4,
        baths: 3,
        listingOwner: "Ali Khan",
        ownerAvatar: "/listingcards/owner1.jpg",
        images: [
            "/listingcards/1.jpg",
            "/listingcards/2.jpg",
            "/listingcards/3.jpg",
        ],
        rentOrSale: "For Sale",
        area: 2500
    },
    {
        id: "2",
        title: "Luxury Apartment in Gulberg",
        address: "San Jose CA, USA",
        datePosted: "7 months",
        price: 120000,
        bed: 2,
        baths: 2,
        listingOwner: "Sara Mehmood",
        ownerAvatar: "/listingcards/owner2.jpg",
        images: [
            "/listingcards/1.jpg",
            "/listingcards/2.jpg",
            "/listingcards/3.jpg",
        ],
        rentOrSale: "For Rent",
        area: 1100
    },
    {
        id: "3",
        title: "Commercial Office Space",
        address: "New York, NY, USA",
        datePosted: "7 months",
        price: 80000000,
        bed: 2,
        baths: 2,
        listingOwner: "Umar Tariq",
        ownerAvatar: "/listingcards/owner3.jpg",
        images: [
            "/listingcards/3.jpg",
            "/listingcards/4.jpg",
            "/listingcards/5.jpg",
        ],
        rentOrSale: "For Sale",
        area: 3000
    },
    {
        id: "4",
        title: "Cozy Studio for Rent",
        address: "San Jose CA, USA",
        datePosted: "7 months",
        price: 45000,
        bed: 1,
        baths: 1,
        listingOwner: "Fariha Zubair",
        ownerAvatar: "/listingcards/owner1.jpg",
        images: [
            "/listingcards/4.jpg",
            "/listingcards/5.jpg",
            "/listingcards/6.jpg",
            "/listingcards/7.jpg",
        ],
        rentOrSale: "For Rent",
        area: 650
    },
    {
        id: "5",
        title: "Cozy Studio for Rent",
        address: "New York, NY, USA",
        datePosted: "7 months",
        price: 45000,
        bed: 1,
        baths: 1,
        listingOwner: "Fariha Zubair",
        ownerAvatar: "/listingcards/owner1.jpg",
        images: [
            "/listingcards/3.jpg",
            "/listingcards/5.jpg",
            "/listingcards/6.jpg",
            "/listingcards/7.jpg",
        ],
        rentOrSale: "For Rent",
        area: 650
    },
    {
        id: "6",
        title: "Cozy Studio for Rent",
        address: "San Jose CA, USA",
        datePosted: "7 months",
        price: 45000,
        bed: 1,
        baths: 1,
        listingOwner: "Fariha Zubair",
        ownerAvatar: "/listingcards/owner1.jpg",
        images: [
            "/listingcards/2.jpg",
            "/listingcards/5.jpg",
            "/listingcards/6.jpg",
            "/listingcards/7.jpg",
        ],
        rentOrSale: "For Rent",
        area: 650
    },
];

export const listings2 = [
    {
        id: "11",
        title: "Modern Family House",
        address: "New York, NY, USA",
        datePosted: "7 months",
        price: 35000000,
        bed: 4,
        baths: 3,
        listingOwner: "Ali Khan",
        ownerAvatar: "/listingcards/owner1.jpg",
        images: [
            "/listingcards/1.jpg",
            "/listingcards/2.jpg",
            "/listingcards/3.jpg",
        ],
        rentOrSale: "For Sale",
        area: 2500,
        type: "house",
    },
    {
        id: "12",
        title: "Luxury Apartment in Gulberg",
        address: "San Jose CA, USA",
        datePosted: "7 months",
        price: 120000,
        bed: 2,
        baths: 2,
        listingOwner: "Sara Mehmood",
        ownerAvatar: "/listingcards/owner2.jpg",
        images: [
            "/listingcards/1.jpg",
            "/listingcards/2.jpg",
            "/listingcards/3.jpg",
        ],
        rentOrSale: "For Rent",
        area: 1100,
        type: "house",
    },
    {
        id: "13",
        title: "Big House",
        address: "New York, NY, USA",
        datePosted: "7 months",
        price: 80000000,
        bed: 2,
        baths: 2,
        listingOwner: "Umar Tariq",
        ownerAvatar: "/listingcards/owner3.jpg",
        images: [
            "/listingcards/3.jpg",
            "/listingcards/4.jpg",
            "/listingcards/5.jpg",
        ],
        rentOrSale: "For Sale",
        area: 3000,
        type: "house",
    },
    {
        id: "14",
        title: "Palace Lahore",
        address: "San Jose CA, USA",
        datePosted: "7 months",
        price: 45000,
        bed: 1,
        baths: 1,
        listingOwner: "Fariha Zubair",
        ownerAvatar: "/listingcards/owner1.jpg",
        images: [
            "/listingcards/4.jpg",
            "/listingcards/5.jpg",
            "/listingcards/6.jpg",
            "/listingcards/7.jpg",
        ],
        rentOrSale: "For Rent",
        area: 650,
        type: "house",
    },
    {
        id: "15",
        title: "Cozy Studio for Rent",
        address: "New York, NY, USA",
        datePosted: "7 months",
        price: 45000,
        bed: 1,
        baths: 1,
        listingOwner: "Fariha Zubair",
        ownerAvatar: "/listingcards/owner1.jpg",
        images: [
            "/listingcards/3.jpg",
            "/listingcards/5.jpg",
            "/listingcards/6.jpg",
            "/listingcards/7.jpg",
        ],
        rentOrSale: "For Rent",
        area: 650,
        type: "house",
    },
    {
        id: "16",
        title: "Cozy Studio for Rent",
        address: "San Jose CA, USA",
        datePosted: "7 months",
        price: 45000,
        bed: 1,
        baths: 1,
        listingOwner: "Fariha Zubair",
        ownerAvatar: "/listingcards/owner1.jpg",
        images: [
            "/listingcards/2.jpg",
            "/listingcards/5.jpg",
            "/listingcards/6.jpg",
            "/listingcards/7.jpg",
        ],
        rentOrSale: "For Rent",
        area: 650,
        type: "house",
    },
    {
        id: "17",
        title: "Studio Apartment for Rent",
        address: "San Jose CA, USA",
        datePosted: "7 months",
        price: 45000,
        bed: 1,
        baths: 1,
        listingOwner: "Fariha Zubair",
        ownerAvatar: "/listingcards/owner1.jpg",
        images: [
            "/listingcards/5.jpg",
            "/listingcards/4.jpg",
            "/listingcards/6.jpg",
            "/listingcards/7.jpg",
        ],
        rentOrSale: "For Rent",
        area: 650,
        type: "apartment",
    },
    {
        id: "18",
        title: "Creator's Studio",
        address: "San Jose CA, USA",
        datePosted: "7 months",
        price: 45000,
        bed: 1,
        baths: 1,
        listingOwner: "Fariha Zubair",
        ownerAvatar: "/listingcards/owner1.jpg",
        images: [
            "/listingcards/6.jpg",
            "/listingcards/5.jpg",
            "/listingcards/6.jpg",
            "/listingcards/7.jpg",
        ],
        rentOrSale: "For Rent",
        area: 650,
        type: "Apartment",
    },
    {
        id: "19",
        title: "PC Hotel",
        address: "San Jose CA, USA",
        datePosted: "7 months",
        price: 45000,
        bed: 1,
        baths: 1,
        listingOwner: "Fariha Zubair",
        ownerAvatar: "/listingcards/owner1.jpg",
        images: [
            "/listingcards/2.jpg",
            "/listingcards/5.jpg",
            "/listingcards/6.jpg",
            "/listingcards/7.jpg",
        ],
        rentOrSale: "For Rent",
        area: 650,
        type: "office",
    },
    {
        id: "20",
        title: "Cozy Beachfront for Rent",
        address: "San Jose CA, USA",
        datePosted: "7 months",
        price: 45000,
        bed: 1,
        baths: 1,
        listingOwner: "Fariha Zubair",
        ownerAvatar: "/listingcards/owner1.jpg",
        images: [
            "/listingcards/2.jpg",
            "/listingcards/5.jpg",
            "/listingcards/6.jpg",
            "/listingcards/7.jpg",
        ],
        rentOrSale: "For Rent",
        area: 650,
        type: "office",
    },
    {
        id: "21",
        title: "Marhaba Palace",
        address: "San Jose CA, USA",
        datePosted: "7 months",
        price: 45000,
        bed: 1,
        baths: 1,
        listingOwner: "Fariha Zubair",
        ownerAvatar: "/listingcards/owner1.jpg",
        images: [
            "/listingcards/2.jpg",
            "/listingcards/5.jpg",
            "/listingcards/6.jpg",
            "/listingcards/7.jpg",
        ],
        rentOrSale: "For Rent",
        area: 650,
        type: "industry",
    },
    {
        id: "22",
        title: "Industry Tyre SHop",
        address: "San Jose CA, USA",
        datePosted: "7 months",
        price: 45000,
        bed: 1,
        baths: 1,
        listingOwner: "Fariha Zubair",
        ownerAvatar: "/listingcards/owner1.jpg",
        images: [
            "/listingcards/2.jpg",
            "/listingcards/5.jpg",
            "/listingcards/6.jpg",
            "/listingcards/7.jpg",
        ],
        rentOrSale: "For Rent",
        area: 650,
        type: "industry",
    },
    {
        id: "23",
        title: "Steel Mill For Rent",
        address: "San Jose CA, USA",
        datePosted: "7 months",
        price: 45000,
        bed: 1,
        baths: 1,
        listingOwner: "Fariha Zubair",
        ownerAvatar: "/listingcards/owner1.jpg",
        images: [
            "/listingcards/4.jpg",
            "/listingcards/5.jpg",
            "/listingcards/6.jpg",
            "/listingcards/7.jpg",
        ],
        rentOrSale: "For Rent",
        area: 650,
        type: "industry",
    },
    {
        id: "24",
        title: "Marhaba Palace",
        address: "San Jose CA, USA",
        datePosted: "7 months",
        price: 45000,
        bed: 1,
        baths: 1,
        listingOwner: "Fariha Zubair",
        ownerAvatar: "/listingcards/owner1.jpg",
        images: [
            "/listingcards/2.jpg",
            "/listingcards/5.jpg",
            "/listingcards/6.jpg",
            "/listingcards/7.jpg",
        ],
        rentOrSale: "For Rent",
        area: 650,
        type: "apartment",
    },
    {
        id: "25",
        title: "Marhaba Palace",
        address: "San Jose CA, USA",
        datePosted: "7 months",
        price: 45000,
        bed: 1,
        baths: 1,
        listingOwner: "Fariha Zubair",
        ownerAvatar: "/listingcards/owner1.jpg",
        images: [
            "/listingcards/3.jpg",
            "/listingcards/5.jpg",
            "/listingcards/6.jpg",
            "/listingcards/7.jpg",
        ],
        rentOrSale: "For Rent",
        area: 650,
        type: "apartment",
    },
    {
        id: "26",
        title: "Last Floor Apartment",
        address: "San Jose CA, USA",
        datePosted: "7 months",
        price: 45000,
        bed: 1,
        baths: 1,
        listingOwner: "Fariha Zubair",
        ownerAvatar: "/listingcards/owner1.jpg",
        images: [
            "/listingcards/4.jpg",
            "/listingcards/5.jpg",
            "/listingcards/6.jpg",
            "/listingcards/7.jpg",
        ],
        rentOrSale: "For Rent",
        area: 650,
        type: "industry",
    },
    {
        id: "27",
        title: "Big Plot for Parking",
        address: "San Jose CA, USA",
        datePosted: "7 months",
        price: 45000,
        bed: 1,
        baths: 1,
        listingOwner: "Fariha Zubair",
        ownerAvatar: "/listingcards/owner1.jpg",
        images: [
            "/listingcards/1.jpg",
            "/listingcards/5.jpg",
            "/listingcards/6.jpg",
            "/listingcards/7.jpg",
        ],
        rentOrSale: "For Rent",
        area: 650,
        type: "land",
    },
    {
        id: "28",
        title: "Country Side Land",
        address: "San Jose CA, USA",
        datePosted: "7 months",
        price: 45000,
        bed: 1,
        baths: 1,
        listingOwner: "Fariha Zubair",
        ownerAvatar: "/listingcards/owner1.jpg",
        images: [
            "/listingcards/2.jpg",
            "/listingcards/5.jpg",
            "/listingcards/6.jpg",
            "/listingcards/7.jpg",
        ],
        rentOrSale: "For Rent",
        area: 650,
        type: "land",
    },
];

// advisor data

export const advisors = [
    {
        name: "Ahsan Raza",
        position: "Project Manager",
        email: "ahsan.raza@example.com",
        phone: "+92 300 1234567",
        avatar: "/advisors/1.jpg",
    },
    {
        name: "Zoya Khan",
        position: "UI/UX Designer",
        email: "zoya.khan@example.com",
        phone: "+92 321 7654321",
        avatar: "/advisors/2.jpg",
    },
    {
        name: "Bilal Ahmed",
        position: "Frontend Developer",
        email: "bilal.ahmed@example.com",
        phone: "+92 334 9876543",
        avatar: "/advisors/3.jpg",
    },
    {
        name: "Fatima Noor",
        position: "Backend Developer",
        email: "fatima.noor@example.com",
        phone: "+92 345 1122334",
        avatar: "/advisors/4.jpg",
    }
];

//   testinomial reviews

export const reviews = [
    {
        ownerAvatar: "/listingcards/owner1.jpg",
        owner: "Hamza Ali",
        title: "Great Experience!",
        description: "The property was exactly as described. The owner was helpful and communication was smooth. Highly recommended!"
    },
    {
        ownerAvatar: "/listingcards/owner2.jpg",
        owner: "Areeba Khan",
        title: "Loved the Location",
        description: "Perfect for a family stay. The neighborhood was peaceful and everything was nearby. Will book again."
    },
    {
        ownerAvatar: "/listingcards/owner3.jpg",
        owner: "Usman Tariq",
        title: "Affordable and Clean",
        description: "Clean and affordable. Just what I needed for my short business trip. The owner made the check-in process seamless."
    },
    {
        ownerAvatar: "/listingcards/owner1.jpg",
        owner: "Sana Malik",
        title: "Spacious & Modern",
        description: "The house was modern and well-maintained. Plenty of space and a beautiful kitchen. Had a great time!"
    },
    {
        ownerAvatar: "/listingcards/owner2.jpg",
        owner: "Bilal Zafar",
        title: "Could be Better",
        description: "The place was nice overall but could use a few improvements like better lighting and faster WiFi."
    }
];
